from __future__ import annotations

import json
import uuid
from typing import TypedDict

import httpx
from langgraph.graph import END, START, StateGraph

from app.config import settings


class AgentState(TypedDict):
    prompt: str
    draft_name: str
    draft_description: str
    draft_trigger: str
    context: str
    trace: list[str]
    analytics: str


async def _local_llm_generate(prompt: str) -> str:
    if settings.llm_provider != "local":
        return "Auto-generated workflow | This workflow was generated by fallback rules | Manual event"
    payload = {
        "model": settings.ollama_model,
        "prompt": (
            "Convert this business automation request into 3 fields separated by | "
            "as: Name | Description | Trigger. Keep it concise.\n"
            f"Request: {prompt}"
        ),
        "stream": False
    }
    async with httpx.AsyncClient(timeout=25) as client:
        response = await client.post(f"{settings.ollama_base_url}/api/generate", json=payload)
        response.raise_for_status()
        return response.json().get("response", "").strip()


async def generate_workflow_from_prompt(prompt: str) -> dict:
    raw = await _local_llm_generate(prompt)
    parts = [p.strip() for p in raw.split("|")]
    name = parts[0] if len(parts) > 0 and parts[0] else "AI Workflow"
    description = parts[1] if len(parts) > 1 and parts[1] else prompt
    trigger = parts[2] if len(parts) > 2 and parts[2] else "Event received"
    return {
        "id": f"wf_{uuid.uuid4().hex[:10]}",
        "name": name,
        "description": description,
        "trigger": trigger,
        "status": "draft",
        "runs_today": 0,
        "graph_json": json.dumps(["orchestrator", "document_intelligence", "communication", "analytics"])
    }


def run_langgraph_pipeline(prompt: str, nodes: list[str]) -> dict:
    def orchestrator(state: AgentState) -> AgentState:
        state["trace"].append("orchestrator: parsed intent")
        return state

    def document_intelligence(state: AgentState) -> AgentState:
        state["context"] = f"retrieved context for: {state['prompt'][:80]}"
        state["trace"].append("document_intelligence: attached RAG context")
        return state

    def communication(state: AgentState) -> AgentState:
        state["trace"].append("communication: drafted outbound message")
        return state

    def analytics(state: AgentState) -> AgentState:
        state["analytics"] = "estimated 37 minutes saved today"
        state["trace"].append("analytics: projected business impact")
        return state

    available = {
        "orchestrator": orchestrator,
        "document_intelligence": document_intelligence,
        "communication": communication,
        "analytics": analytics
    }
    selected = [node for node in nodes if node in available] or ["orchestrator", "analytics"]

    graph = StateGraph(AgentState)
    for node in selected:
        graph.add_node(node, available[node])

    graph.add_edge(START, selected[0])
    for i in range(len(selected) - 1):
        graph.add_edge(selected[i], selected[i + 1])
    graph.add_edge(selected[-1], END)

    compiled = graph.compile()
    result = compiled.invoke(
        {
            "prompt": prompt,
            "draft_name": "",
            "draft_description": "",
            "draft_trigger": "",
            "context": "",
            "trace": [],
            "analytics": ""
        }
    )
    return {
        "trace": result.get("trace", []),
        "analytics": result.get("analytics", "no analytics"),
        "context": result.get("context", "")
    }
